version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/projects/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      docker-all:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/projects/website"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      docker-all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      github-actions-all:
        patterns:
          - "*"
