---
kind: pipeline
type: kubernetes
name: ssr-deploy

steps:
  - name: Build Docker Image
    image: plugins/docker
    settings:
      repo: fascinated/ssr
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - latest

  - name: Deploy to Kubernetes
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: https://10.0.69.162:6443
      kubernetes_token:
        from_secret: kubernetes_token
      namespace: public-services
      deployment: ssr
      repo: fascinated/ssr
      tag: latest
