---
kind: pipeline
type: kubernetes
name: ssr-deploy

steps:
  - name: Build Docker Image
    image: plugins/docker
    settings:
      registry: git.fascinated.cc
      repo: git.fascinated.cc/fascinated/scoresaber-reloaded
      username:
        from_secret: username
      password:
        from_secret: token
      tags:
        - latest
