---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ssr-staging-ingress
  namespace: public-services
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ssr-staging.fascinated.cc`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: ssr
          port: 80
  tls:
    secretName: fascinated-cc
