version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./projects/backend/Dockerfile
    container_name: backend-service
    ports:
      - "8080:3000"  # This maps IPv4 port for incoming connections
    networks:
      - default      # For IPv4 connectivity to the container
      - ipv6-network # For outbound IPv6 connectivity
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - "traefik.http.routers.backend.rule=Host(`ssr-api.fascinated.cc`) && PathPrefix(`/`)"
      - traefik.http.routers.backend.entryPoints=http
      - traefik.http.services.backend.loadbalancer.server.port=8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
networks:
  default:
    driver: bridge
  ipv6-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bc8:1201:430::/64
          gateway: 2001:bc8:1201:430::1