import HMDIcon from "@/components/hmd-icon";
import { TwitchIcon } from "@/components/icons/twitch-icon";
import { ChartBarIcon as HeroOutlineChartBarIcon } from "@heroicons/react/24/outline";
import {
  ArrowPathIcon,
  ExclamationTriangleIcon,
  GlobeAmericasIcon,
  CubeIcon as HeroCubeIcon,
  StarIcon as HeroStarIcon,
  TrophyIcon as HeroTrophyIcon,
  SparklesIcon,
} from "@heroicons/react/24/solid";
import {
  CheckIcon as RadixCheckIcon,
  ChevronDownIcon as RadixChevronDownIcon,
  ChevronUpIcon as RadixChevronUpIcon,
  CubeIcon as RadixCubeIcon,
  MagnifyingGlassIcon as RadixMagnifyingGlassIcon,
  PersonIcon as RadixPersonIcon,
  QuestionMarkCircledIcon as RadixQuestionMarkCircledIcon,
  StarFilledIcon as RadixStarFilledIcon,
} from "@radix-ui/react-icons";
import {
  AlertCircle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Award,
  BarChart3,
  BombIcon,
  Box,
  BrickWallIcon,
  CalculatorIcon,
  CalendarDays,
  ChartBarIcon,
  CheckCircleIcon,
  ChevronDown,
  ChevronDownIcon,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Clock,
  ClockIcon,
  CloudDownloadIcon,
  Cog,
  Crosshair,
  CrownIcon,
  Database,
  Download,
  DownloadIcon,
  DrumIcon,
  ExternalLink,
  ExternalLinkIcon,
  Eye,
  EyeIcon,
  FileX,
  Filter,
  Flag,
  Flame,
  FlameIcon,
  Frown,
  Gauge,
  GaugeIcon,
  Globe,
  Hash,
  Heart,
  History,
  HomeIcon,
  Image as ImageIcon,
  LinkIcon,
  ListOrdered,
  Loader2,
  LoaderCircle,
  Medal,
  Monitor,
  Move,
  Music,
  MusicIcon,
  Palette,
  Pause,
  Play,
  Plus,
  PlayCircle,
  PlayCircleIcon,
  PlayIcon,
  Search,
  SearchIcon,
  SearchX,
  Settings,
  ShieldCheck,
  Snowflake,
  Star,
  StarIcon,
  SwordIcon,
  Target,
  TimerIcon,
  TrendingUpIcon,
  TriangleIcon,
  Trophy,
  TrophyIcon,
  Undo2,
  User,
  UserMinus,
  UserPlus,
  UserRound,
  UserSearch,
  Users,
  UsersIcon,
  X,
  XIcon,
  Zap,
} from "lucide-react";

export const SharedIcons = {
  // Player stats & platforms
  MedalsIcon: Medal,
  PerformancePointsIcon: Trophy,
  GlobalRankIcon: GlobeAmericasIcon,
  HeadMountedDisplayIcon: HMDIcon,
  MedalsPlatformLogoIcon: Medal,
  PlayerStreakIcon: Flame,
  VerifiedPlayerIcon: ShieldCheck,
  TwitchProfileIcon: TwitchIcon,

  // Navbar
  RankingNavIcon: TrendingUpIcon,
  MedalsNavIcon: Medal,
  MapsNavIcon: MusicIcon,
  OverlayNavIcon: RadixCubeIcon,
  TopScoresNavIcon: TrophyIcon,
  SettingsNavIcon: Settings,
  FriendsNavIcon: UsersIcon,

  // Player profile charts
  PlayerRankingViewIcon: GlobeAmericasIcon,
  PlayerAccuracyViewIcon: TrendingUpIcon,
  PlayerScoresViewIcon: SwordIcon,
  PlayerScoresGraphViewIcon: ChartBarIcon,
  PlayerSkillTriangleViewIcon: TriangleIcon,
  PlayerPpCalculatorViewIcon: CalculatorIcon,
  PlayerAccuracyBadgesViewIcon: Award,
  ExpandPlayerStatsIcon: ChevronDown,
  CollapsePlayerStatsIcon: ChevronUp,

  // Score list sort tabs & controls
  TopScoresTabIcon: TrendingUpIcon,
  RecentScoresTabIcon: ClockIcon,
  PerformancePointsSortIcon: Trophy,
  DateSortIcon: Clock,
  MissesSortIcon: XIcon,
  AccuracySortIcon: Target,
  ScoreValueSortIcon: BarChart3,
  MaxComboSortIcon: Hash,
  MedalsSortIcon: Medal,
  SortDescendingIcon: ArrowDown,
  SortAscendingIcon: ArrowUp,

  // AccSaber score sorts
  AccSaberApSortIcon: Trophy,
  AccSaberDateSortIcon: ClockIcon,
  AccSaberAccuracySortIcon: Target,
  AccSaberRankSortIcon: Trophy,
  AccSaberOverallSortIcon: BarChart3,
  AccSaberTechAccuracySortIcon: Zap,
  AccSaberStandardAccuracySortIcon: Gauge,
  AccSaberTrueAccuracySortIcon: Crosshair,
  AccSaberBadgeIcon: SparklesIcon,
  AccSaberGlobalRankIcon: GlobeAmericasIcon,

  // Score feed modes
  GlobalScoresModeIcon: GlobeAmericasIcon,
  FriendsScoresModeIcon: RadixPersonIcon,
  HistoryScoresModeIcon: TrendingUpIcon,

  // Playlist & score filters
  AllScoresFilterIcon: Filter,
  RankedScoresFilterIcon: Trophy,
  UnrankedScoresFilterIcon: MusicIcon,
  SnipePlaylistIcon: Crosshair,
  SelfPlaylistPlayerIcon: User,

  // Maps
  MapsLeaderboardsTabIcon: HeroTrophyIcon,
  MapsRankingQueueTabIcon: TrendingUpIcon,
  MapsExternalLinkIcon: ExternalLinkIcon,
  MapLengthStatIcon: TimerIcon,
  MapBpmStatIcon: MusicIcon,
  MapNpsStatIcon: DrumIcon,
  MapNjsStatIcon: GaugeIcon,
  MapNotesStatIcon: HeroCubeIcon,
  MapBombsStatIcon: BombIcon,
  MapObstaclesStatIcon: BrickWallIcon,
  StatScorePausesIcon: Pause,
  StatJumpDistanceIcon: Move,
  StatFullComboAccuracyIcon: Target,
  StatRankedPlayCountIcon: ListOrdered,
  StatTotalRankedScoreIcon: BarChart3,
  StatAverageRankedAccuracyIcon: Target,
  StatTotalPlayCountIcon: Play,
  StatTotalScoreIcon: BarChart3,
  StatJoinedDateIcon: CalendarDays,
  StatTrackedSinceIcon: Clock,
  StatPlayerRolesIcon: ShieldCheck,
  StatPeakRankIcon: TrendingUpIcon,
  StatPlusOnePpIcon: Plus,
  StatAccuracyGradeIcon: Award,
  RankedMapsPlaylistIcon: CrownIcon,
  QualifiedMapsPlaylistIcon: CheckCircleIcon,
  RankingQueuePlaylistIcon: ClockIcon,
  TrendingMapsPlaylistIcon: FlameIcon,
  CustomPlaylistIcon: Star,

  // Leaderboards & scores UI
  DifficultyStarIcon: StarIcon,
  QualifiedLeaderboardStarIcon: RadixStarFilledIcon,
  ScoreStarBadgeIcon: HeroStarIcon,
  LeaderboardStarHistoryIcon: StarIcon,
  LeaderboardEmptyStateIcon: HeroOutlineChartBarIcon,
  LeaderboardPpChartIcon: ChartBarIcon,
  ScoreHistoryChartIcon: ChartBarIcon,
  PlayMapIcon: PlayIcon,
  PreviewMapIcon: PlayCircleIcon,
  MapCheckIcon: EyeIcon,
  OneClickInstallIcon: DownloadIcon,
  InstallMapToGameIcon: CloudDownloadIcon,
  ExpandLeaderboardRowIcon: ChevronDown,
  RankingQueueExpandIcon: ChevronDownIcon,

  // Friends
  AddFriendIcon: UserPlus,
  RemoveFriendIcon: UserMinus,
  RemoveFriendFromListIcon: XIcon,

  // Search
  SearchIcon: Search,
  SearchFieldIcon: SearchIcon,
  SearchLoadingIcon: LoaderCircle,
  SearchNoResultsIcon: SearchX,
  ClearSearchInputIcon: XIcon,
  SearchPlayersIcon: Users,
  SearchLeaderboardsMusicIcon: Music,
  SearchLeaderboardsPlayersIcon: UserSearch,
  NotFoundSearchIcon: SearchIcon,

  // Ranking pages
  GlobalPlayersRankingIcon: GlobeAmericasIcon,
  RankingPageLinkIcon: LinkIcon,

  // Score page actions
  ScoreDateIcon: CalendarDays,
  WatchReplayIcon: PlayCircle,
  ViewLeaderboardIcon: ListOrdered,
  PlayerProfileButtonIcon: UserRound,
  ScoreEditorIcon: Cog,
  FlagScoreIcon: Flag,
  UndoScoreEditIcon: Undo2,

  // Medals
  MedalsInfoIcon: Medal,
  MedalsRankingHeaderIcon: Medal,
  OverlayPlayerMedalsIcon: Medal,

  // Landing page
  OpenSourceBadgeIcon: Star,
  OpenSourceArrowIcon: ArrowRight,
  ComprehensiveDataFeatureIcon: Database,
  FriendSystemFeatureIcon: Users,
  AdvancedAnalyticsFeatureIcon: BarChart3,
  GlobalLeaderboardsFeatureIcon: Globe,
  CustomOverlaysFeatureIcon: Monitor,
  CommunityDrivenFeatureIcon: Heart,

  // Settings
  WebsiteSettingsCategoryIcon: Globe,
  ScoreSettingsCategoryIcon: Box,
  PlayerSettingsCategoryIcon: User,
  PlayerHistorySettingsIcon: History,
  OpenReplayOnScorePageSettingsIcon: Play,
  WebsiteCoverImageSettingsIcon: ImageIcon,
  WebsiteSnowfallSettingsIcon: Snowflake,
  WebsiteGlobalSettingsIcon: Globe,
  WebsiteThemeSettingsIcon: Palette,

  // Overlay builder
  OverlayPlayerLayerIcon: User,
  OverlayPreviewLayerIcon: Eye,
  OverlayDisplayLayerIcon: Monitor,

  // Downloads
  DownloadPlaylistIcon: Download,

  // Pagination & loading
  PaginationLoadingIcon: ArrowPathIcon,
  PaginationFirstPageIcon: ChevronsLeft,
  PaginationPreviousPageIcon: ChevronLeft,
  PaginationNextPageIcon: ChevronRight,
  PaginationLastPageIcon: ChevronsRight,
  AvatarRefreshIcon: ArrowPathIcon,
  PageLoadingIcon: Loader2,

  // UI primitives
  DialogCloseIcon: XIcon,
  FilterClearIcon: XIcon,
  ComboBoxToggleIcon: ChevronsUpDown,
  ComboBoxClearIcon: X,
  SelectCheckIcon: RadixCheckIcon,
  SelectScrollUpIcon: RadixChevronUpIcon,
  SelectScrollDownIcon: RadixChevronDownIcon,
  CheckboxCheckIcon: RadixCheckIcon,
  CommandPaletteSearchIcon: RadixMagnifyingGlassIcon,
  UnknownMapCharacteristicIcon: RadixQuestionMarkCircledIcon,

  // Errors & notices
  PageErrorIcon: Frown,
  GoHomeIcon: HomeIcon,
  WarningAlertIcon: AlertCircle,
  MissingContentIcon: FileX,
  StatsUnavailableIcon: BarChart3,
  SiteNoticeWarningIcon: ExclamationTriangleIcon,

  // Footer & misc
  ExternalNavigationIcon: ExternalLink,
  ScoresGraphFriendIcon: Users,
  ScoresGraphRemoveIcon: X,
} as const;

export type SharedIcon = (typeof SharedIcons)[keyof typeof SharedIcons];

/** Icons usable with `className` / `aria-hidden` only (excludes HMD, which needs `hmd`). */
export type SharedDecorativeIcon = Exclude<SharedIcon, typeof SharedIcons.HeadMountedDisplayIcon>;
