import { describe, expect, test } from "bun:test";
import { beatLeaderScoreRowToType } from "../../../../src/db/converter/beatleader-score";
import type { BeatLeaderScoreRow } from "../../../../src/db/schema";

function baseRow(overrides: Partial<BeatLeaderScoreRow> = {}): BeatLeaderScoreRow {
  return {
    id: 99,
    playerId: "bl-player",
    songHash: "abc123",
    leaderboardId: "leaderboard-1",
    songDifficulty: "Expert",
    songCharacteristic: "Standard",
    songScore: 1_000_000,
    pauses: 2,
    fcAccuracy: 0.98,
    fullCombo: true,
    savedReplay: true,
    leftHandAccuracy: 0.91,
    rightHandAccuracy: 0.93,
    misses: 1,
    missedNotes: 2,
    bombCuts: 3,
    wallsHit: 4,
    badCuts: 5,
    improvementScore: 50_000,
    improvementPauses: 1,
    improvementMisses: 1,
    improvementMissedNotes: 1,
    improvementBombCuts: 0,
    improvementWallsHit: 0,
    improvementBadCuts: 0,
    improvementLeftHandAccuracy: 0.01,
    improvementRightHandAccuracy: 0.02,
    timestamp: new Date("2024-06-15T12:00:00.000Z"),
    ...overrides,
  };
}

describe("beatLeaderScoreRowToType", () => {
  const cases = [
    {
      name: "maps all fields from a full row",
      row: baseRow(),
      expected: {
        playerId: "bl-player",
        songHash: "abc123",
        leaderboardId: "leaderboard-1",
        scoreId: 99,
        difficulty: "Expert",
        characteristic: "Standard",
        pauses: 2,
        fcAccuracy: 0.98,
        fullCombo: true,
        handAccuracy: { left: 0.91, right: 0.93 },
        misses: {
          misses: 1,
          missedNotes: 2,
          bombCuts: 3,
          wallsHit: 4,
          badCuts: 5,
        },
        scoreImprovement: {
          score: 50_000,
          pauses: 1,
          misses: {
            misses: 1,
            missedNotes: 1,
            bombCuts: 0,
            wallsHit: 0,
            badCuts: 0,
          },
          handAccuracy: { left: 0.01, right: 0.02 },
        },
        savedReplay: true,
        timestamp: new Date("2024-06-15T12:00:00.000Z"),
      },
    },
    {
      name: "defaults savedReplay to false when null",
      row: baseRow({ savedReplay: null as unknown as boolean }),
      expected: {
        playerId: "bl-player",
        songHash: "abc123",
        leaderboardId: "leaderboard-1",
        scoreId: 99,
        difficulty: "Expert",
        characteristic: "Standard",
        pauses: 2,
        fcAccuracy: 0.98,
        fullCombo: true,
        handAccuracy: { left: 0.91, right: 0.93 },
        misses: {
          misses: 1,
          missedNotes: 2,
          bombCuts: 3,
          wallsHit: 4,
          badCuts: 5,
        },
        scoreImprovement: {
          score: 50_000,
          pauses: 1,
          misses: {
            misses: 1,
            missedNotes: 1,
            bombCuts: 0,
            wallsHit: 0,
            badCuts: 0,
          },
          handAccuracy: { left: 0.01, right: 0.02 },
        },
        savedReplay: false,
        timestamp: new Date("2024-06-15T12:00:00.000Z"),
      },
    },
    {
      name: "maps zero and empty edge values",
      row: baseRow({
        id: 0,
        playerId: "",
        songHash: "",
        leaderboardId: "",
        songDifficulty: "Easy",
        songCharacteristic: "NoArrows",
        songScore: 0,
        pauses: 0,
        fcAccuracy: 0,
        fullCombo: false,
        savedReplay: false,
        leftHandAccuracy: 0,
        rightHandAccuracy: 0,
        misses: 0,
        missedNotes: 0,
        bombCuts: 0,
        wallsHit: 0,
        badCuts: 0,
        improvementScore: 0,
        improvementPauses: 0,
        improvementMisses: 0,
        improvementMissedNotes: 0,
        improvementBombCuts: 0,
        improvementWallsHit: 0,
        improvementBadCuts: 0,
        improvementLeftHandAccuracy: 0,
        improvementRightHandAccuracy: 0,
        timestamp: new Date(0),
      }),
      expected: {
        playerId: "",
        songHash: "",
        leaderboardId: "",
        scoreId: 0,
        difficulty: "Easy",
        characteristic: "NoArrows",
        pauses: 0,
        fcAccuracy: 0,
        fullCombo: false,
        handAccuracy: { left: 0, right: 0 },
        misses: {
          misses: 0,
          missedNotes: 0,
          bombCuts: 0,
          wallsHit: 0,
          badCuts: 0,
        },
        scoreImprovement: {
          score: 0,
          pauses: 0,
          misses: {
            misses: 0,
            missedNotes: 0,
            bombCuts: 0,
            wallsHit: 0,
            badCuts: 0,
          },
          handAccuracy: { left: 0, right: 0 },
        },
        savedReplay: false,
        timestamp: new Date(0),
      },
    },
  ] as const;

  for (const { name, row, expected } of cases) {
    test(name, () => {
      expect(beatLeaderScoreRowToType(row)).toEqual(expected);
    });
  }
});
