import { env } from "@ssr/common/env";
import { Modifier } from "@ssr/common/score/modifier";
import { describe, expect, test } from "bun:test";
import { scoreSaberScoreRowToType } from "../../../../src/db/converter/scoresaber-score";
import type { ScoreSaberScoreHistoryRow, ScoreSaberScoreRow } from "../../../../src/db/schema";

function baseScoreRow(overrides: Partial<ScoreSaberScoreRow> = {}): ScoreSaberScoreRow {
  return {
    scoreId: 5001,
    playerId: "player-1",
    leaderboardId: 200,
    difficulty: "Expert",
    characteristic: "Standard",
    score: 950_000,
    accuracy: 0.97,
    pp: 250.5,
    medals: 3,
    missedNotes: 2,
    badCuts: 1,
    maxCombo: 400,
    fullCombo: false,
    modifiers: ["NF"],
    hmd: "Quest",
    rightController: "oculus",
    leftController: "oculus",
    timestamp: new Date("2024-05-01T00:00:00.000Z"),
    ...overrides,
  };
}

function baseHistoryRow(overrides: Partial<ScoreSaberScoreHistoryRow> = {}): ScoreSaberScoreHistoryRow {
  return {
    id: 1,
    scoreId: 6001,
    playerId: "player-2",
    leaderboardId: 201,
    difficulty: "Hard",
    characteristic: "OneSaber",
    score: 800_000,
    accuracy: 0.9,
    pp: 100,
    medals: 0,
    missedNotes: 0,
    badCuts: 0,
    maxCombo: 300,
    fullCombo: true,
    modifiers: null,
    hmd: "Unknown",
    rightController: null,
    leftController: null,
    timestamp: new Date("2024-05-02T00:00:00.000Z"),
    ...overrides,
  };
}

describe("scoreSaberScoreRowToType", () => {
  const cases = [
    {
      name: "maps score row with modifier codes",
      row: baseScoreRow(),
      expected: {
        playerId: "player-1",
        leaderboardId: 200,
        scoreId: 5001,
        difficulty: "Expert",
        characteristic: "Standard",
        score: 950_000,
        accuracy: 0.97,
        pp: 250.5,
        weight: 0,
        rank: -1,
        misses: 3,
        missedNotes: 2,
        badCuts: 1,
        maxCombo: 400,
        fullCombo: false,
        modifiers: [Modifier.NF],
        playerInfo: {
          id: "player-1",
          avatar: env.NEXT_PUBLIC_WEBSITE_URL + "/assets/unknown.png",
        },
        hmd: "Quest",
        rightController: "oculus",
        leftController: "oculus",
        timestamp: new Date("2024-05-01T00:00:00.000Z"),
      },
    },
    {
      name: "maps history row",
      row: baseHistoryRow(),
      expected: {
        playerId: "player-2",
        leaderboardId: 201,
        scoreId: 6001,
        difficulty: "Hard",
        characteristic: "OneSaber",
        score: 800_000,
        accuracy: 0.9,
        pp: 100,
        weight: 0,
        rank: -1,
        misses: 0,
        missedNotes: 0,
        badCuts: 0,
        maxCombo: 300,
        fullCombo: true,
        modifiers: [],
        playerInfo: {
          id: "player-2",
          avatar: env.NEXT_PUBLIC_WEBSITE_URL + "/assets/unknown.png",
        },
        hmd: "Unknown",
        rightController: null,
        leftController: null,
        timestamp: new Date("2024-05-02T00:00:00.000Z"),
      },
    },
    {
      name: "handles empty modifiers and null controllers",
      row: baseScoreRow({
        modifiers: [],
        rightController: null,
        leftController: null,
        missedNotes: 0,
        badCuts: 0,
        fullCombo: true,
        score: 0,
        accuracy: 0,
        pp: 0,
      }),
      expected: {
        playerId: "player-1",
        leaderboardId: 200,
        scoreId: 5001,
        difficulty: "Expert",
        characteristic: "Standard",
        score: 0,
        accuracy: 0,
        pp: 0,
        weight: 0,
        rank: -1,
        misses: 0,
        missedNotes: 0,
        badCuts: 0,
        maxCombo: 400,
        fullCombo: true,
        modifiers: [],
        playerInfo: {
          id: "player-1",
          avatar: env.NEXT_PUBLIC_WEBSITE_URL + "/assets/unknown.png",
        },
        hmd: "Quest",
        rightController: null,
        leftController: null,
        timestamp: new Date("2024-05-01T00:00:00.000Z"),
      },
    },
    {
      name: "normalizes legacy modifier labels",
      row: baseScoreRow({ modifiers: ["No Fail"] }),
      expected: {
        playerId: "player-1",
        leaderboardId: 200,
        scoreId: 5001,
        difficulty: "Expert",
        characteristic: "Standard",
        score: 950_000,
        accuracy: 0.97,
        pp: 250.5,
        weight: 0,
        rank: -1,
        misses: 3,
        missedNotes: 2,
        badCuts: 1,
        maxCombo: 400,
        fullCombo: false,
        modifiers: [Modifier.NF],
        playerInfo: {
          id: "player-1",
          avatar: env.NEXT_PUBLIC_WEBSITE_URL + "/assets/unknown.png",
        },
        hmd: "Quest",
        rightController: "oculus",
        leftController: "oculus",
        timestamp: new Date("2024-05-01T00:00:00.000Z"),
      },
    },
    {
      name: "treats undefined modifiers as empty",
      row: baseScoreRow({ modifiers: undefined as unknown as string[] }),
      expected: {
        playerId: "player-1",
        leaderboardId: 200,
        scoreId: 5001,
        difficulty: "Expert",
        characteristic: "Standard",
        score: 950_000,
        accuracy: 0.97,
        pp: 250.5,
        weight: 0,
        rank: -1,
        misses: 3,
        missedNotes: 2,
        badCuts: 1,
        maxCombo: 400,
        fullCombo: false,
        modifiers: [],
        playerInfo: {
          id: "player-1",
          avatar: env.NEXT_PUBLIC_WEBSITE_URL + "/assets/unknown.png",
        },
        hmd: "Quest",
        rightController: "oculus",
        leftController: "oculus",
        timestamp: new Date("2024-05-01T00:00:00.000Z"),
      },
    },
  ] as const;

  for (const { name, row, expected } of cases) {
    test(name, () => {
      expect(scoreSaberScoreRowToType(row)).toEqual(expected);
    });
  }
});
