import { describe, expect, test } from "bun:test";
import { scoreSaberAccountRowToType } from "../../../../src/db/converter/scoresaber-account";
import type { ScoreSaberAccountRow } from "../../../../src/db/schema";

function baseRow(overrides: Partial<ScoreSaberAccountRow> = {}): ScoreSaberAccountRow {
  return {
    id: "account-1",
    name: "Player One",
    country: "US",
    avatar: "https://example.com/avatar.png",
    peakRank: null,
    peakRankTimestamp: null,
    seededScores: true,
    seededBeatLeaderScores: false,
    trackReplays: true,
    inactive: false,
    banned: false,
    hmd: "Quest",
    pp: 1234.5,
    medals: 10,
    medalsRank: 100,
    medalsCountryRank: 5,
    currentStreak: 3,
    longestStreak: 7,
    lastPlayedDate: null,
    trackedSince: new Date("2023-01-01T00:00:00.000Z"),
    joinedDate: new Date("2022-06-01T00:00:00.000Z"),
    ...overrides,
  };
}

describe("scoreSaberAccountRowToType", () => {
  const cases = [
    {
      name: "maps all fields without peak rank",
      row: baseRow(),
      expected: {
        id: "account-1",
        name: "Player One",
        avatar: "https://example.com/avatar.png",
        country: "US",
        peakRank: undefined,
        seededScores: true,
        seededBeatLeaderScores: false,
        trackReplays: true,
        inactive: false,
        banned: false,
        hmd: "Quest",
        pp: 1234.5,
        medals: 10,
        medalsRank: 100,
        medalsCountryRank: 5,
        currentStreak: 3,
        longestStreak: 7,
        trackedSince: new Date("2023-01-01T00:00:00.000Z"),
        joinedDate: new Date("2022-06-01T00:00:00.000Z"),
      },
    },
    {
      name: "maps peak rank when rank and timestamp are present",
      row: baseRow({
        peakRank: 42,
        peakRankTimestamp: new Date("2024-03-01T10:00:00.000Z"),
      }),
      expected: {
        id: "account-1",
        name: "Player One",
        avatar: "https://example.com/avatar.png",
        country: "US",
        peakRank: { rank: 42, timestamp: new Date("2024-03-01T10:00:00.000Z") },
        seededScores: true,
        seededBeatLeaderScores: false,
        trackReplays: true,
        inactive: false,
        banned: false,
        hmd: "Quest",
        pp: 1234.5,
        medals: 10,
        medalsRank: 100,
        medalsCountryRank: 5,
        currentStreak: 3,
        longestStreak: 7,
        trackedSince: new Date("2023-01-01T00:00:00.000Z"),
        joinedDate: new Date("2022-06-01T00:00:00.000Z"),
      },
    },
    {
      name: "omits peak rank when only rank is present",
      row: baseRow({ peakRank: 1, peakRankTimestamp: null }),
      expected: {
        id: "account-1",
        name: "Player One",
        avatar: "https://example.com/avatar.png",
        country: "US",
        peakRank: undefined,
        seededScores: true,
        seededBeatLeaderScores: false,
        trackReplays: true,
        inactive: false,
        banned: false,
        hmd: "Quest",
        pp: 1234.5,
        medals: 10,
        medalsRank: 100,
        medalsCountryRank: 5,
        currentStreak: 3,
        longestStreak: 7,
        trackedSince: new Date("2023-01-01T00:00:00.000Z"),
        joinedDate: new Date("2022-06-01T00:00:00.000Z"),
      },
    },
    {
      name: "omits peak rank when only timestamp is present",
      row: baseRow({ peakRank: null, peakRankTimestamp: new Date("2024-03-01T10:00:00.000Z") }),
      expected: {
        id: "account-1",
        name: "Player One",
        avatar: "https://example.com/avatar.png",
        country: "US",
        peakRank: undefined,
        seededScores: true,
        seededBeatLeaderScores: false,
        trackReplays: true,
        inactive: false,
        banned: false,
        hmd: "Quest",
        pp: 1234.5,
        medals: 10,
        medalsRank: 100,
        medalsCountryRank: 5,
        currentStreak: 3,
        longestStreak: 7,
        trackedSince: new Date("2023-01-01T00:00:00.000Z"),
        joinedDate: new Date("2022-06-01T00:00:00.000Z"),
      },
    },
    {
      name: "normalizes null country to Unknown",
      row: baseRow({ country: null, pp: 0, medals: 0, medalsRank: 0, medalsCountryRank: 0 }),
      expected: {
        id: "account-1",
        name: "Player One",
        avatar: "https://example.com/avatar.png",
        country: "Unknown",
        peakRank: undefined,
        seededScores: true,
        seededBeatLeaderScores: false,
        trackReplays: true,
        inactive: false,
        banned: false,
        hmd: "Quest",
        pp: 0,
        medals: 0,
        medalsRank: 0,
        medalsCountryRank: 0,
        currentStreak: 3,
        longestStreak: 7,
        trackedSince: new Date("2023-01-01T00:00:00.000Z"),
        joinedDate: new Date("2022-06-01T00:00:00.000Z"),
      },
    },
    {
      name: "maps empty string id and zero streaks",
      row: baseRow({
        id: "",
        name: "",
        currentStreak: 0,
        longestStreak: 0,
        inactive: true,
        banned: true,
      }),
      expected: {
        id: "",
        name: "",
        avatar: "https://example.com/avatar.png",
        country: "US",
        peakRank: undefined,
        seededScores: true,
        seededBeatLeaderScores: false,
        trackReplays: true,
        inactive: true,
        banned: true,
        hmd: "Quest",
        pp: 1234.5,
        medals: 10,
        medalsRank: 100,
        medalsCountryRank: 5,
        currentStreak: 0,
        longestStreak: 0,
        trackedSince: new Date("2023-01-01T00:00:00.000Z"),
        joinedDate: new Date("2022-06-01T00:00:00.000Z"),
      },
    },
  ] as const;

  for (const { name, row, expected } of cases) {
    test(name, () => {
      expect(scoreSaberAccountRowToType(row)).toEqual(expected);
    });
  }
});
