CREATE TABLE "scoresaber-leaderboards" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"songHash" varchar(64) NOT NULL,
	"songName" varchar(255) NOT NULL,
	"songSubName" varchar(255) NOT NULL,
	"songAuthorName" varchar(255) NOT NULL,
	"levelAuthorName" varchar(255) NOT NULL,
	"maxScore" integer NOT NULL,
	"difficulty" varchar(32) NOT NULL,
	"characteristic" varchar(32) NOT NULL,
	"rawDifficulty" varchar(32) NOT NULL,
	"ranked" boolean NOT NULL,
	"qualified" boolean NOT NULL,
	"stars" double precision,
	"rankedDate" timestamp,
	"qualifiedDate" timestamp,
	"plays" integer NOT NULL,
	"dailyPlays" integer NOT NULL,
	"seededScores" boolean NOT NULL,
	"cachedSongArt" boolean NOT NULL,
	"timestamp" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scoresaber-score-history" (
	"id" serial PRIMARY KEY NOT NULL,
	"playerId" varchar(32) NOT NULL,
	"leaderboardId" integer NOT NULL,
	"scoreId" varchar(32) NOT NULL,
	"difficulty" varchar(32) NOT NULL,
	"characteristic" varchar(32) NOT NULL,
	"score" integer NOT NULL,
	"accuracy" double precision NOT NULL,
	"pp" double precision DEFAULT 0 NOT NULL,
	"missedNotes" integer NOT NULL,
	"badCuts" integer NOT NULL,
	"maxCombo" integer NOT NULL,
	"fullCombo" boolean NOT NULL,
	"modifiers" varchar(32)[] DEFAULT '{}' NOT NULL,
	"hmd" varchar(32),
	"rightController" varchar(32),
	"leftController" varchar(32),
	"timestamp" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scoresaber-scores" (
	"scoreId" varchar(32) PRIMARY KEY NOT NULL,
	"playerId" varchar(32) NOT NULL,
	"leaderboardId" integer NOT NULL,
	"difficulty" varchar(32) NOT NULL,
	"characteristic" varchar(32) NOT NULL,
	"score" integer NOT NULL,
	"accuracy" double precision NOT NULL,
	"pp" double precision DEFAULT 0 NOT NULL,
	"missedNotes" integer NOT NULL,
	"badCuts" integer NOT NULL,
	"maxCombo" integer NOT NULL,
	"fullCombo" boolean NOT NULL,
	"modifiers" varchar(32)[] DEFAULT '{}' NOT NULL,
	"hmd" varchar(32),
	"rightController" varchar(32),
	"leftController" varchar(32),
	"beatLeaderScoreId" integer,
	"timestamp" timestamp NOT NULL
);
