CREATE TABLE "scoresaber-player-statistics" (
	"playerId" varchar(32) PRIMARY KEY NOT NULL,
	"rank" integer,
	"countryRank" integer,
	"medals" integer,
	"pp" double precision,
	"plusOnePp" double precision,
	"totalScore" double precision,
	"totalRankedScore" double precision,
	"rankedScores" integer,
	"unrankedScores" integer,
	"totalRankedScores" integer,
	"totalUnrankedScores" integer,
	"totalScores" integer,
	"averageRankedAccuracy" double precision,
	"averageUnrankedAccuracy" double precision,
	"averageAccuracy" double precision,
	"aPlays" integer,
	"sPlays" integer,
	"spPlays" integer,
	"ssPlays" integer,
	"sspPlays" integer,
	"godPlays" integer
);
