apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoresaber-reloaded-website
  namespace: public-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scoresaber-reloaded-website
  template:
    metadata:
      labels:
        app: scoresaber-reloaded-website
    spec:
      containers:
        - name: scoresaber-reloaded-website-container
          image: git.fascinated.cc/fascinated/scoresaber-reloaded-website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m # 1 vCPU
              memory: 256Mi
          env:
            - name: NEXT_PUBLIC_SITE_URL
              valueFrom:
                secretKeyRef:
                  name: ssr-secret
                  key: NEXT_PUBLIC_SITE_URL
